services:
  app:
    container_name: e-commerce-backend
    build: 
      context: ./backend
    ports:
      - 3333:3333
    volumes:
      - ./backend:/home/node/app:cached
    env_file:
    - ./backend/.env
    depends_on:
      - db
  frontend:
    container_name: e-commerce-frontend
    build: 
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/home/next/app:cached            
    env_file:
      - ./frontend/.env        
    depends_on:
      - app
  db:
    container_name: e-commerce-db
    image: postgres:13-alpine
    ports:
      - 5432:5432
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
